### ISSUE TITLE
outdated body example on 3.2.

### ISSUE THREAD

**Issue by selbstmord** [88/mojang-api-docs#13] opened 2022-01-13 20:15 UTC
the body given is: 

```
{
    "Properties": {
        "AuthMethod": "RPS",
        "SiteName": "user.auth.xboxlive.com",
        "RpsTicket": "d=ACCESS_TOKEN_HERE"
    },
    "RelyingParty": "http://auth.xboxlive.com",
    "TokenType": "JWT"
}
```

however the `d=` causes status code 400 and an empty response body.

therefore it should be changed to 

```
{
    "Properties": {
        "AuthMethod": "RPS",
        "SiteName": "user.auth.xboxlive.com",
        "RpsTicket": "ACCESS_TOKEN_HERE"
    },
    "RelyingParty": "http://auth.xboxlive.com",
    "TokenType": "JWT"
}
```

edit: as i can see there was a pr for this recently https://github.com/88/mojang-api-docs/pull/8, they must have changed it?

**Comment by bigfoot547** [comment] 2022-01-13 22:53
I have just tested this and it works with the `d=` there. Do you have a curl command that you can reproduce this behavior with?

**Comment by selbstmord** [comment] 2022-01-13 22:56
I can send my python code if you would like.

**Comment by bigfoot547** [comment] 2022-01-13 22:56
Go for it

**Comment by drainer** [comment] 2022-01-14 07:51
Hi there, yes this was added because of #8. The d= parameter should still be there from my last testing. Please send the code you're using with the endpoint, until this is figured out I'm leaving it open. Just commenting so you know I've seen it

**Comment by selbstmord** [comment] 2022-01-14 11:49
```
import requests
import re
import urllib.parse

email = ""
password = ""

session = requests.Session()

req = session.get("https://login.live.com/oauth20_authorize.srf?client_id=000000004C12AE6F&redirect_uri=https://login.live.com/oauth20_desktop.srf&scope=service::user.auth.xboxlive.com::MBI_SSL&display=touch&response_type=token&locale=en")
body = req.text

sftttag = re.search('value="(.+?)"', body).group(1)
urlpost = re.search("urlPost:'(.+?)'", body).group(1)

req = session.post(
    urlpost,
    headers={"Content-Type": "application/x-www-form-urlencoded"},
    data=urllib.parse.urlencode({
        "login": email,
        "loginfmt": email,
        "passwd": password,
        "PPFT": sftttag
    }),
    allow_redirects=True
)
body = req.text

if(req.url == urlpost):
    if("Sign in to" in body):
        print("invalid login")
    if("Help us protect your account" in body):
        print("2fa enabled")

rawdata = req.url.split("#")[1]
data = dict(item.split("=") for item in rawdata.split("&"))

req = session.post(
    "https://user.auth.xboxlive.com/user/authenticate",
    headers={
        "Accept": "application/json",
    },
    json={
        "RelyingParty": "http://auth.xboxlive.com",
        "TokenType": "JWT",
        "Properties": {
            "AuthMethod": "RPS",
            "SiteName": "user.auth.xboxlive.com",
            "RpsTicket": data["access_token"],
        }
    }
)
print(req.text)
print(req.status_code)
```

result for me in  ->
```
{"IssueInstant":"2022-01-14T11:47:40.5279333Z","NotAfter":"2022-01-28T11:47:40.5279333Z","Token":"...","DisplayClaims":{"xui":[{"uhs":"..."}]}}
200
```

**Comment by selbstmord** [comment] 2022-01-14 16:54
> I'm getting too many different reports of it working for some and not working for others. The ideal solution that I see here is just > to add a warning that it may work with d= and may not work other times, unless we can narrow down the cause of this.

sounds good to me, big company's endpoints are just weird sometimes, might be a region thing

**Comment by drainer** [comment] 2022-01-14 16:57
Oh, are you unquoting the access and refresh tokens in the code? I don't know why that would fix anything but maybe try it.

```
data = dict(item.split("=") for item in rawdata.split("&"))
data["access_token"] = requests.utils.unquote(data["access_token"])
data["refresh_token"] = requests.utils.unquote(data["refresh_token"])
```

**Comment by selbstmord** [comment] 2022-01-14 16:59
Causes the same result for me.

**Comment by drainer** [comment] 2022-01-14 17:13
I just tested using your code (only thing changed was experimental 2fa support because I don't have any accounts without 2fa). I was able to log in without the use of d=. I guess the best thing right now is to add the warning. Leaving this open until the warning is actually added.

**Comment by drainer** [comment] 2022-01-14 17:21
How does this look as the warning?

**Note:** You may need to add `d=` before the access token. Some users report they cannot sign into Xbox Live unless they add `d=` before the token (like so: `d=ACCESS_TOKEN_HERE`). Others report the exact opposite, being able to sign in without `d=`. I (the author of this article) report being able to only sign in without `d=`, so that is what I will show here in this example body.

**Comment by selbstmord** [comment] 2022-01-14 17:23
Oh, I was just gonna make a pr for this, yeah that looks good. You should mention the fact that unquoting the body is also optional (e.g. for better readability)

**Comment by bigfoot547** [comment] 2022-01-14 17:28
Could the difference be that @selbstmord used the username+password authentication and that I used oauth2?

**Comment by selbstmord** [comment] 2022-01-14 17:29
> Could the difference be that @selbstmord used the username+password authentication and that I used oauth2?

Is the EPthe same?

**Comment by bigfoot547** [comment] 2022-01-14 17:32
Yes, it's the same endpoint, but it's the only difference I can find. Lemme post my code, one second.

**Comment by bigfoot547** [comment] 2022-01-14 17:42
Here is code that works (provided you have a valid application on Azure):
```python
mport requests

REDIR_URI="http://localhost"
CLIENT_ID="00000000-1111-4222-3333-444455556666"
USER_AGENT="test_script/0.1.0"

dest_url = requests.Request("GET", "https://login.live.com/oauth20_authorize.srf", params={
  "client_id": CLIENT_ID,
  "response_type": "code",
  "redirect_uri": REDIR_URI,
  "scope": "XboxLive.signin XboxLive.offline_access"
})

print(f"OAuth URL: {dest_url.prepare().url}")
oauth_token = input("Paste the code here: ").strip()

response = requests.post("https://login.live.com/oauth20_token.srf", headers={"User-agent": USER_AGENT}, data={
  "client_id": CLIENT_ID, # The client ID of your application in Azure
  "code": oauth_token,    # The token received from the authorization link thingy
  "grant_type": "authorization_code",
  "redirect_uri": REDIR_URI # The redirect URI (probably http://localhost)
})

if response.status_code != 200:
  print(f"Error: {response.status_code} - {response.headers} - {response.text}")
  exit()

access_token = response.json()["access_token"]

response = requests.post("https://user.auth.xboxlive.com/user/authenticate", headers={"User-agent": USER_AGENT, "Content-type": "application/json", "Accept": "application/json"}, json={
  "Properties": {
    "AuthMethod": "RPS",
    "SiteName": "user.auth.xboxlive.com",
    "RpsTicket": f"d={access_token}"
  },
  "RelyingParty": "http://auth.xboxlive.com",
  "TokenType": "JWT"
})

print(response.status_code)
print("-----------------")
print(response.headers)
print("-----------------")
print(response.text)
```

**Comment by drainer** [comment] 2022-01-14 17:53
Unable to test this right now. Will add a "there is a possibility that it depends on oauth or user:pass authentication" bit to the warning.

I won't add the unquoting bit because it isn't a breaking change and I've encountered issues when I don't unquote at times.

**Comment by drainer** [comment] 2022-01-14 18:33
@selbstmord, good catch with the session reminder as well. Seems I forgot to put that warning in when I first made the docs. Working on the update now and will close this when it's pushed.

**Comment by drainer** [comment] 2022-01-14 18:55
Updated the docs. Thank you both for your contributions!

**Closed** 2022-01-14 18:54 UTC

**Comment by selbstmord** [comment] 2022-01-14 19:00
could you change the entry to "Tayhay" instead of selbstmord?

**Comment by drainer** [comment] 2022-01-14 19:10
Changed the entry.

What would examples contain? Lists of libraries to interact with the API? Code snippets to do it yourself?

**Comment by selbstmord** [comment] 2022-01-14 19:12
Code snippets, for example python code to login.

**Comment by drainer** [comment] 2022-01-14 19:28
I can put this in the list of things to work on, but it isn't a priority right now
